#!/bin/sh
# Daemon for qmi. Restart modem.
# autor https://github.com/yosh781

trap "logger 'Modem watchdog stopped'; exit 0" INT TERM

if ! uci -q get network.wan >/dev/null; then
    logger "Interface wan not found in network config, exiting"
    exit 0
fi

LTEPROTO=$(uci -q get network.wan.proto)
if [ "$LTEPROTO" != "qmi" ]; then
    logger "WAN interface is not using qmi, exiting"
    exit 0
fi

AUTOCONNECT=$(uci -q get network.wan.autoconnect)
if [ "$AUTOCONNECT" != "1" ]; then
    logger "WAN autoconnect is disabled, exiting"
    exit 0
fi

while true; do
    sleep 15
    output=$(qmicli -d /dev/cdc-wdm0 --dms-get-operating-mode 2>&1)
	sleep 1
    qmicli_exit_code=$?

    if echo "$output" | grep -q "offline" || [ "$qmicli_exit_code" -ne 0 ]; then
    logger "Modem is reboot..."
    echo -e "AT+CFUN=1,1\r" > /dev/ttyUSB2
	sleep 60
    exit 0
fi
        
    LTESTATUS=$(qmicli -d /dev/cdc-wdm0 --wds-get-packet-service-status 2>/dev/null | grep -c '"connected"')
   
    if [ "$LTESTATUS" -eq 0 ]; then
        logger "Modem is not connected to network, trying to reconnect..."
	    ifdown wan && ifup wan
        sleep 10       
       
    fi

    
done

exit 0
